version: "3"

services:

  website:
    image: e4e/muenzi/website:1.0.0
    build:
      context: .
    ports:
       - "8008:80"
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www-muenzi.rule=Host(`www.muenzi.elternfuereltern.de`)"
      - "traefik.http.routers.www-muenzi.entrypoints=websecure"
      - "traefik.http.routers.www-muenzi.tls.certresolver=le"
      - "traefik.docker.network=web"


networks:
  web:
    external: true

