version: "3"

services:

  website:
    container_name: ${SCHOOL}_www
    image: e4e/${SCHOOL}/website:1.0.0
    build:
      context: .
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www-${SCHOOL}.rule=Host(`www.${SCHOOL}.elternfuereltern.de`)"
      - "traefik.http.routers.www-${SCHOOL}.entrypoints=websecure"
      - "traefik.http.routers.www-${SCHOOL}.tls.certresolver=le"
      - "traefik.docker.network=web"


networks:
  web:
    external: true

